### ISSUE TITLE
Weekend masih Checkin Checkou

### ISSUE THREAD

**Issue by tukangdeploy** [subekti404dev/darwinbox-inout#1]
bang knapa kalo weekend tetep checkin & checkout ?
![Screenshot_4](https://github.com/subekti404dev/darwinbox-inout/assets/86710676/892844c6-90ba-43af-8aca-6db78214c062)

**Comment by subekti404dev** [comment]
sorry mang, iya kemaren ada yg missed ...
udah difix disini mang https://github.com/subekti404dev/darwinbox-inout/commit/4b588150efc3df2b371753444ba3f74758c402c7
bisa di pull master lagi / docker image latest :pray:

**Comment by subekti404dev** [comment]
ku close ya issue-nya. kalau masih ada, nanti re-open :pray:
